/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerScore = IDL.Record({
  'playerId' : IDL.Nat,
  'score' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScoringMethod = IDL.Variant({
  'roundBased' : IDL.Null,
  'endOfGame' : IDL.Null,
});
export const NertsRules = IDL.Record({
  'winTarget' : IDL.Nat,
  'scoringDetails' : IDL.Text,
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : IDL.Text,
  'gameEndCondition' : IDL.Text,
});
export const GameType = IDL.Variant({
  'flip7' : IDL.Record({
    'targetScore' : IDL.Nat,
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  }),
  'skyjo' : IDL.Record({
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  }),
  'nerts' : NertsRules,
  'milleBornes' : IDL.Record({
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  }),
});
export const Fields__1 = IDL.Record({
  'id' : IDL.Nat,
  'gamesPlayed' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const Fields = IDL.Record({ 'playerId' : IDL.Nat, 'score' : IDL.Nat });
export const Fields__2 = IDL.Record({
  'playerScores' : IDL.Vec(Fields),
  'roundNumber' : IDL.Nat,
});
export const GameSession = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'players' : IDL.Vec(Fields__1),
  'finalScores' : IDL.Opt(IDL.Vec(Fields)),
  'flip7TargetScore' : IDL.Opt(IDL.Nat),
  'gameType' : GameType,
  'rounds' : IDL.Vec(Fields__2),
  'nertsWinTarget' : IDL.Opt(IDL.Nat),
});
export const PlayerProfile = IDL.Record({
  'id' : IDL.Nat,
  'gamesPlayed' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGameSession' : IDL.Func(
      [GameType, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createPlayerProfile' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAllGameSessions' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
  'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getAllPlayerProfilesByGamesPlayed' : IDL.Func(
      [],
      [IDL.Vec(PlayerProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameSession' : IDL.Func([IDL.Nat], [GameSession], ['query']),
  'getPlayerProfile' : IDL.Func([IDL.Nat], [PlayerProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerScore = IDL.Record({ 'playerId' : IDL.Nat, 'score' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScoringMethod = IDL.Variant({
    'roundBased' : IDL.Null,
    'endOfGame' : IDL.Null,
  });
  const NertsRules = IDL.Record({
    'winTarget' : IDL.Nat,
    'scoringDetails' : IDL.Text,
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  });
  const GameType = IDL.Variant({
    'flip7' : IDL.Record({
      'targetScore' : IDL.Nat,
      'scoringMethod' : ScoringMethod,
      'rulesSummary' : IDL.Text,
      'gameEndCondition' : IDL.Text,
    }),
    'skyjo' : IDL.Record({
      'scoringMethod' : ScoringMethod,
      'rulesSummary' : IDL.Text,
      'gameEndCondition' : IDL.Text,
    }),
    'nerts' : NertsRules,
    'milleBornes' : IDL.Record({
      'scoringMethod' : ScoringMethod,
      'rulesSummary' : IDL.Text,
      'gameEndCondition' : IDL.Text,
    }),
  });
  const Fields__1 = IDL.Record({
    'id' : IDL.Nat,
    'gamesPlayed' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const Fields = IDL.Record({ 'playerId' : IDL.Nat, 'score' : IDL.Nat });
  const Fields__2 = IDL.Record({
    'playerScores' : IDL.Vec(Fields),
    'roundNumber' : IDL.Nat,
  });
  const GameSession = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'players' : IDL.Vec(Fields__1),
    'finalScores' : IDL.Opt(IDL.Vec(Fields)),
    'flip7TargetScore' : IDL.Opt(IDL.Nat),
    'gameType' : GameType,
    'rounds' : IDL.Vec(Fields__2),
    'nertsWinTarget' : IDL.Opt(IDL.Nat),
  });
  const PlayerProfile = IDL.Record({
    'id' : IDL.Nat,
    'gamesPlayed' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGameSession' : IDL.Func(
        [GameType, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createPlayerProfile' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAllGameSessions' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
    'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getAllPlayerProfilesByGamesPlayed' : IDL.Func(
        [],
        [IDL.Vec(PlayerProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameSession' : IDL.Func([IDL.Nat], [GameSession], ['query']),
    'getPlayerProfile' : IDL.Func([IDL.Nat], [PlayerProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };