/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Flip7Rules {
  'targetScore' : bigint,
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : string,
  'gameEndCondition' : string,
}
export interface GameSession {
  'id' : bigint,
  'phase10WinTarget' : [] | [bigint],
  'owner' : Principal,
  'createdAt' : bigint,
  'isActive' : boolean,
  'players' : Array<PlayerProfile>,
  'finalScores' : [] | [Array<PlayerScore>],
  'flip7TargetScore' : [] | [bigint],
  'gameType' : GameType,
  'rounds' : Array<Round>,
  'phase10Progress' : [] | [Phase10Progress],
  'nertsWinTarget' : [] | [bigint],
}
export type GameType = { 'flip7' : Flip7Rules } |
  { 'skyjo' : SkyjoRules } |
  { 'nerts' : NertsRules } |
  { 'genericGame' : GenericGameRules } |
  { 'milleBornes' : MilleBornesRules } |
  { 'phase10' : Phase10Rules };
export interface GenericGameRules {
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : string,
  'gameEndCondition' : string,
}
export interface MilleBornesRules {
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : string,
  'gameEndCondition' : string,
}
export interface NertsRules {
  'winTarget' : bigint,
  'scoringDetails' : string,
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : string,
  'gameEndCondition' : string,
}
export interface Phase10Completion {
  'playerId' : bigint,
  'completed' : boolean,
}
export type Phase10Progress = Array<PlayerPhase>;
export interface Phase10Rules {
  'winTarget' : bigint,
  'scoringDetails' : string,
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : string,
  'gameEndCondition' : string,
}
export interface PlayerPhase { 'currentPhase' : bigint, 'playerId' : bigint }
export interface PlayerProfile {
  'id' : bigint,
  'gamesPlayed' : bigint,
  'owner' : Principal,
  'name' : string,
  'wins' : bigint,
  'totalScore' : bigint,
  'averageScore' : bigint,
}
export interface PlayerScore { 'playerId' : bigint, 'score' : bigint }
export interface Round {
  'playerScores' : Array<PlayerScore>,
  'roundNumber' : bigint,
}
export type ScoringMethod = { 'roundBased' : null } |
  { 'endOfGame' : null };
export interface SkyjoRules {
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : string,
  'gameEndCondition' : string,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRound' : ActorMethod<[bigint, bigint, Array<PlayerScore>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGameSession' : ActorMethod<
    [GameType, Array<bigint>, [] | [bigint], [] | [bigint], [] | [bigint]],
    bigint
  >,
  'createPlayerProfile' : ActorMethod<[string], bigint>,
  'getAllGameSessions' : ActorMethod<[], Array<GameSession>>,
  'getAllPlayerProfiles' : ActorMethod<[], Array<PlayerProfile>>,
  'getAllPlayerProfilesByGamesPlayed' : ActorMethod<[], Array<PlayerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameSession' : ActorMethod<[bigint], GameSession>,
  'getPlayerProfile' : ActorMethod<[bigint], PlayerProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPhase10Round' : ActorMethod<
    [bigint, bigint, Array<PlayerScore>, Array<Phase10Completion>],
    undefined
  >,
  'updateRound' : ActorMethod<[bigint, bigint, Array<PlayerScore>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];