/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerScore = IDL.Record({
  'playerId' : IDL.Nat,
  'score' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScoringMethod = IDL.Variant({
  'roundBased' : IDL.Null,
  'endOfGame' : IDL.Null,
});
export const Flip7Rules = IDL.Record({
  'targetScore' : IDL.Nat,
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : IDL.Text,
  'gameEndCondition' : IDL.Text,
});
export const SkyjoRules = IDL.Record({
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : IDL.Text,
  'gameEndCondition' : IDL.Text,
});
export const NertsRules = IDL.Record({
  'winTarget' : IDL.Nat,
  'scoringDetails' : IDL.Text,
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : IDL.Text,
  'gameEndCondition' : IDL.Text,
});
export const GenericGameRules = IDL.Record({
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : IDL.Text,
  'gameEndCondition' : IDL.Text,
});
export const MilleBornesRules = IDL.Record({
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : IDL.Text,
  'gameEndCondition' : IDL.Text,
});
export const Phase10Rules = IDL.Record({
  'winTarget' : IDL.Nat,
  'scoringDetails' : IDL.Text,
  'scoringMethod' : ScoringMethod,
  'rulesSummary' : IDL.Text,
  'gameEndCondition' : IDL.Text,
});
export const GameType = IDL.Variant({
  'flip7' : Flip7Rules,
  'skyjo' : SkyjoRules,
  'nerts' : NertsRules,
  'genericGame' : GenericGameRules,
  'milleBornes' : MilleBornesRules,
  'phase10' : Phase10Rules,
});
export const PlayerProfile = IDL.Record({
  'id' : IDL.Nat,
  'gamesPlayed' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const Round = IDL.Record({
  'playerScores' : IDL.Vec(PlayerScore),
  'roundNumber' : IDL.Nat,
});
export const PlayerPhase = IDL.Record({
  'currentPhase' : IDL.Nat,
  'playerId' : IDL.Nat,
});
export const Phase10Progress = IDL.Vec(PlayerPhase);
export const GameSession = IDL.Record({
  'id' : IDL.Nat,
  'phase10WinTarget' : IDL.Opt(IDL.Nat),
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'players' : IDL.Vec(PlayerProfile),
  'finalScores' : IDL.Opt(IDL.Vec(PlayerScore)),
  'flip7TargetScore' : IDL.Opt(IDL.Nat),
  'gameType' : GameType,
  'rounds' : IDL.Vec(Round),
  'phase10Progress' : IDL.Opt(Phase10Progress),
  'nertsWinTarget' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Phase10Completion = IDL.Record({
  'playerId' : IDL.Nat,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGameSession' : IDL.Func(
      [
        GameType,
        IDL.Vec(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'createPlayerProfile' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAllGameSessions' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
  'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getAllPlayerProfilesByGamesPlayed' : IDL.Func(
      [],
      [IDL.Vec(PlayerProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameSession' : IDL.Func([IDL.Nat], [GameSession], ['query']),
  'getPlayerProfile' : IDL.Func([IDL.Nat], [PlayerProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPhase10Round' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore), IDL.Vec(Phase10Completion)],
      [],
      [],
    ),
  'updateRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerScore = IDL.Record({ 'playerId' : IDL.Nat, 'score' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScoringMethod = IDL.Variant({
    'roundBased' : IDL.Null,
    'endOfGame' : IDL.Null,
  });
  const Flip7Rules = IDL.Record({
    'targetScore' : IDL.Nat,
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  });
  const SkyjoRules = IDL.Record({
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  });
  const NertsRules = IDL.Record({
    'winTarget' : IDL.Nat,
    'scoringDetails' : IDL.Text,
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  });
  const GenericGameRules = IDL.Record({
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  });
  const MilleBornesRules = IDL.Record({
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  });
  const Phase10Rules = IDL.Record({
    'winTarget' : IDL.Nat,
    'scoringDetails' : IDL.Text,
    'scoringMethod' : ScoringMethod,
    'rulesSummary' : IDL.Text,
    'gameEndCondition' : IDL.Text,
  });
  const GameType = IDL.Variant({
    'flip7' : Flip7Rules,
    'skyjo' : SkyjoRules,
    'nerts' : NertsRules,
    'genericGame' : GenericGameRules,
    'milleBornes' : MilleBornesRules,
    'phase10' : Phase10Rules,
  });
  const PlayerProfile = IDL.Record({
    'id' : IDL.Nat,
    'gamesPlayed' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const Round = IDL.Record({
    'playerScores' : IDL.Vec(PlayerScore),
    'roundNumber' : IDL.Nat,
  });
  const PlayerPhase = IDL.Record({
    'currentPhase' : IDL.Nat,
    'playerId' : IDL.Nat,
  });
  const Phase10Progress = IDL.Vec(PlayerPhase);
  const GameSession = IDL.Record({
    'id' : IDL.Nat,
    'phase10WinTarget' : IDL.Opt(IDL.Nat),
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'players' : IDL.Vec(PlayerProfile),
    'finalScores' : IDL.Opt(IDL.Vec(PlayerScore)),
    'flip7TargetScore' : IDL.Opt(IDL.Nat),
    'gameType' : GameType,
    'rounds' : IDL.Vec(Round),
    'phase10Progress' : IDL.Opt(Phase10Progress),
    'nertsWinTarget' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Phase10Completion = IDL.Record({
    'playerId' : IDL.Nat,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGameSession' : IDL.Func(
        [
          GameType,
          IDL.Vec(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'createPlayerProfile' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAllGameSessions' : IDL.Func([], [IDL.Vec(GameSession)], ['query']),
    'getAllPlayerProfiles' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getAllPlayerProfilesByGamesPlayed' : IDL.Func(
        [],
        [IDL.Vec(PlayerProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameSession' : IDL.Func([IDL.Nat], [GameSession], ['query']),
    'getPlayerProfile' : IDL.Func([IDL.Nat], [PlayerProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPhase10Round' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore), IDL.Vec(Phase10Completion)],
        [],
        [],
      ),
    'updateRound' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(PlayerScore)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };