/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type GameType = {
    __kind__: "flip7";
    flip7: {
        targetScore: bigint;
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    __kind__: "skyjo";
    skyjo: {
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    __kind__: "nerts";
    nerts: NertsRules;
} | {
    __kind__: "milleBornes";
    milleBornes: {
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
};
export interface Fields__1 {
    id: bigint;
    gamesPlayed: bigint;
    owner: Principal;
    name: string;
    wins: bigint;
    totalScore: bigint;
    averageScore: bigint;
}
export interface Fields__2 {
    playerScores: Array<Fields>;
    roundNumber: bigint;
}
export interface NertsRules {
    winTarget: bigint;
    scoringDetails: string;
    scoringMethod: ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
}
export interface PlayerProfile {
    id: bigint;
    gamesPlayed: bigint;
    owner: Principal;
    name: string;
    wins: bigint;
    totalScore: bigint;
    averageScore: bigint;
}
export interface PlayerScore {
    playerId: bigint;
    score: bigint;
}
export interface Fields {
    playerId: bigint;
    score: bigint;
}
export interface GameSession {
    id: bigint;
    owner: Principal;
    createdAt: bigint;
    isActive: boolean;
    players: Array<Fields__1>;
    finalScores?: Array<Fields>;
    flip7TargetScore?: bigint;
    gameType: GameType;
    rounds: Array<Fields__2>;
    nertsWinTarget?: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export enum ScoringMethod {
    roundBased = "roundBased",
    endOfGame = "endOfGame"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRound(gameId: bigint, roundNumber: bigint, scores: Array<PlayerScore>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGameSession(gameType: GameType, playerIds: Array<bigint>, nertsWinTarget: bigint | null, flip7TargetScore: bigint | null): Promise<bigint>;
    createPlayerProfile(name: string): Promise<bigint>;
    getAllGameSessions(): Promise<Array<GameSession>>;
    getAllPlayerProfiles(): Promise<Array<PlayerProfile>>;
    getAllPlayerProfilesByGamesPlayed(): Promise<Array<PlayerProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGameSession(gameId: bigint): Promise<GameSession>;
    getPlayerProfile(profileId: bigint): Promise<PlayerProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Fields as _Fields, Fields__1 as _Fields__1, Fields__2 as _Fields__2, GameSession as _GameSession, GameType as _GameType, NertsRules as _NertsRules, ScoringMethod as _ScoringMethod, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRound(arg0: bigint, arg1: bigint, arg2: Array<PlayerScore>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRound(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRound(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGameSession(arg0: GameType, arg1: Array<bigint>, arg2: bigint | null, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGameSession(to_candid_GameType_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGameSession(to_candid_GameType_n3(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createPlayerProfile(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayerProfile(arg0);
            return result;
        }
    }
    async getAllGameSessions(): Promise<Array<GameSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGameSessions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGameSessions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayerProfiles(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerProfiles();
            return result;
        }
    }
    async getAllPlayerProfilesByGamesPlayed(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerProfilesByGamesPlayed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerProfilesByGamesPlayed();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameSession(arg0: bigint): Promise<GameSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameSession(arg0);
                return from_candid_GameSession_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameSession(arg0);
            return from_candid_GameSession_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProfile(arg0: bigint): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_GameSession_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameSession): GameSession {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GameType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameType): GameType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_NertsRules_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NertsRules): NertsRules {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ScoringMethod_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScoringMethod): ScoringMethod {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Fields>]): Array<Fields> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: Principal;
    createdAt: bigint;
    isActive: boolean;
    players: Array<_Fields__1>;
    finalScores: [] | [Array<_Fields>];
    flip7TargetScore: [] | [bigint];
    gameType: _GameType;
    rounds: Array<_Fields__2>;
    nertsWinTarget: [] | [bigint];
}): {
    id: bigint;
    owner: Principal;
    createdAt: bigint;
    isActive: boolean;
    players: Array<Fields__1>;
    finalScores?: Array<Fields>;
    flip7TargetScore?: bigint;
    gameType: GameType;
    rounds: Array<Fields__2>;
    nertsWinTarget?: bigint;
} {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        isActive: value.isActive,
        players: value.players,
        finalScores: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.finalScores)),
        flip7TargetScore: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.flip7TargetScore)),
        gameType: from_candid_GameType_n17(_uploadFile, _downloadFile, value.gameType),
        rounds: value.rounds,
        nertsWinTarget: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.nertsWinTarget))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    targetScore: bigint;
    scoringMethod: _ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
}): {
    targetScore: bigint;
    scoringMethod: ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
} {
    return {
        targetScore: value.targetScore,
        scoringMethod: from_candid_ScoringMethod_n20(_uploadFile, _downloadFile, value.scoringMethod),
        rulesSummary: value.rulesSummary,
        gameEndCondition: value.gameEndCondition
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scoringMethod: _ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
}): {
    scoringMethod: ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
} {
    return {
        scoringMethod: from_candid_ScoringMethod_n20(_uploadFile, _downloadFile, value.scoringMethod),
        rulesSummary: value.rulesSummary,
        gameEndCondition: value.gameEndCondition
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    winTarget: bigint;
    scoringDetails: string;
    scoringMethod: _ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
}): {
    winTarget: bigint;
    scoringDetails: string;
    scoringMethod: ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
} {
    return {
        winTarget: value.winTarget,
        scoringDetails: value.scoringDetails,
        scoringMethod: from_candid_ScoringMethod_n20(_uploadFile, _downloadFile, value.scoringMethod),
        rulesSummary: value.rulesSummary,
        gameEndCondition: value.gameEndCondition
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flip7: {
        targetScore: bigint;
        scoringMethod: _ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    skyjo: {
        scoringMethod: _ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    nerts: _NertsRules;
} | {
    milleBornes: {
        scoringMethod: _ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
}): {
    __kind__: "flip7";
    flip7: {
        targetScore: bigint;
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    __kind__: "skyjo";
    skyjo: {
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    __kind__: "nerts";
    nerts: NertsRules;
} | {
    __kind__: "milleBornes";
    milleBornes: {
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} {
    return "flip7" in value ? {
        __kind__: "flip7",
        flip7: from_candid_record_n19(_uploadFile, _downloadFile, value.flip7)
    } : "skyjo" in value ? {
        __kind__: "skyjo",
        skyjo: from_candid_record_n22(_uploadFile, _downloadFile, value.skyjo)
    } : "nerts" in value ? {
        __kind__: "nerts",
        nerts: from_candid_NertsRules_n23(_uploadFile, _downloadFile, value.nerts)
    } : "milleBornes" in value ? {
        __kind__: "milleBornes",
        milleBornes: from_candid_record_n22(_uploadFile, _downloadFile, value.milleBornes)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roundBased: null;
} | {
    endOfGame: null;
}): ScoringMethod {
    return "roundBased" in value ? ScoringMethod.roundBased : "endOfGame" in value ? ScoringMethod.endOfGame : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameSession>): Array<GameSession> {
    return value.map((x)=>from_candid_GameSession_n13(_uploadFile, _downloadFile, x));
}
function to_candid_GameType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): _GameType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NertsRules_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NertsRules): _NertsRules {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ScoringMethod_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScoringMethod): _ScoringMethod {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    targetScore: bigint;
    scoringMethod: ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
}): {
    targetScore: bigint;
    scoringMethod: _ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
} {
    return {
        targetScore: value.targetScore,
        scoringMethod: to_candid_ScoringMethod_n6(_uploadFile, _downloadFile, value.scoringMethod),
        rulesSummary: value.rulesSummary,
        gameEndCondition: value.gameEndCondition
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scoringMethod: ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
}): {
    scoringMethod: _ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
} {
    return {
        scoringMethod: to_candid_ScoringMethod_n6(_uploadFile, _downloadFile, value.scoringMethod),
        rulesSummary: value.rulesSummary,
        gameEndCondition: value.gameEndCondition
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    winTarget: bigint;
    scoringDetails: string;
    scoringMethod: ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
}): {
    winTarget: bigint;
    scoringDetails: string;
    scoringMethod: _ScoringMethod;
    rulesSummary: string;
    gameEndCondition: string;
} {
    return {
        winTarget: value.winTarget,
        scoringDetails: value.scoringDetails,
        scoringMethod: to_candid_ScoringMethod_n6(_uploadFile, _downloadFile, value.scoringMethod),
        rulesSummary: value.rulesSummary,
        gameEndCondition: value.gameEndCondition
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "flip7";
    flip7: {
        targetScore: bigint;
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    __kind__: "skyjo";
    skyjo: {
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    __kind__: "nerts";
    nerts: NertsRules;
} | {
    __kind__: "milleBornes";
    milleBornes: {
        scoringMethod: ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
}): {
    flip7: {
        targetScore: bigint;
        scoringMethod: _ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    skyjo: {
        scoringMethod: _ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} | {
    nerts: _NertsRules;
} | {
    milleBornes: {
        scoringMethod: _ScoringMethod;
        rulesSummary: string;
        gameEndCondition: string;
    };
} {
    return value.__kind__ === "flip7" ? {
        flip7: to_candid_record_n10(_uploadFile, _downloadFile, value.flip7)
    } : value.__kind__ === "skyjo" ? {
        skyjo: to_candid_record_n5(_uploadFile, _downloadFile, value.skyjo)
    } : value.__kind__ === "nerts" ? {
        nerts: to_candid_NertsRules_n8(_uploadFile, _downloadFile, value.nerts)
    } : value.__kind__ === "milleBornes" ? {
        milleBornes: to_candid_record_n5(_uploadFile, _downloadFile, value.milleBornes)
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScoringMethod): {
    roundBased: null;
} | {
    endOfGame: null;
} {
    return value == ScoringMethod.roundBased ? {
        roundBased: null
    } : value == ScoringMethod.endOfGame ? {
        endOfGame: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
